### ISSUE TITLE
Question - Consumption of my electrical devices

### ISSUE THREAD

**Issue by r0m1CH** [fmartinou/tydom2mqtt#168]
Hi,

I use to get my electrical consumption of my heating devices through tydom2mqtt.
But It seems that it does not work or maybe I misconfigured something ?

Tydom2mqtt : latest version
Delta Dore - Tydom Pro
HA 2023.11.3
Delta Dore Calybox 2020 WT
All under Docker 

It seems that I only have climate sensor that works well but no consumption at all.

Any idea  for me ?

Thanks

**Comment by frnicolas** [comment]
I have the same problem.
with Calybox 1020 and a Tydom PRO
on thee MQTT module in HA, I see the sensor going ot of range. and after a normal value.
See this video

https://github.com/fmartinou/tydom2mqtt/assets/48152656/344be46f-ae51-4826-bab7-60a99303c1bb

**Comment by NCoiby** [comment]
@frnicolas , I guess this behaviour started from the 1st of january ?
The "out of range" value is the total since the installation of your tydom, while the "normal" value is the yearly total.
This issue has been reported here #68, but there is no fix yet.

Apart from that, are your consumption values updating correctly ? Mine are only updated everytime I restart my MQTT broker. Maybe it is your case as well @r0m1CH ?

**Comment by r0m1CH** [comment]
I switched to something else to control power consumption
